name: Build, Test, and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Run Tests and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonar todo el historial para an치lisis preciso

      # Paso 2: Configuraci칩n de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Paso 4: Ejecutar pruebas unitarias
      - name: Run unit tests
        run: |
          pytest --junitxml=test-results.xml --cov=. --cov-report=xml

      # Paso 5: Ejecutar an치lisis est치tico en SonarCloud
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token para acceder a datos del repo (PRs, commits)
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Token generado desde SonarCloud
